# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZegoUIKitCallWithInvitation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZegoUIKitCallWithInvitation
  #pod 'ZegoUIKit'

  pod 'ZIM'
  pod 'ZegoExpressEngine'
end
