# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZegoUIKitLineOffCallWithInvitationDemo' do
  use_frameworks!

  #pod 'Toast-Swift'
  #pod 'ZegoUIKitPrebuiltCall'
  #pod 'ZegoUIKitSignalingPlugin'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY'] = ''
             end
        end
      end
    end

end
