# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZegoUIKitOffLineCallWithInvitationDemo' do
  use_frameworks!

  pod 'Toast-Swift'
  pod 'ZegoUIKitPrebuiltCall', '>=2.7.0'
  pod 'ZegoUIKitSignalingPlugin', '>=2.4.0'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY'] = ''
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
             end
        end
      end
    end

end
