# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ZegoUIKitOffLineCallWithInvitationDemo' do
  use_frameworks!

  pod 'Toast-Swift'
  
  pod 'ZegoUIKitPrebuiltCall', '>=2.13.12'
  pod 'ZegoUIKitSignalingPlugin', '>=2.5.0'
  pod 'ZegoUIKitAppleCallKitPlugin', '>=1.0.3'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY'] = ''
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
             end
        end
      end
    end

end
