# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ZegoCallDemoOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZegoCallDemoOC
  pod 'ZegoUIKitPrebuiltCall'

  target 'ZegoCallDemoOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZegoCallDemoOCUITests' do
    # Pods for testing
  end

end
